title: Lena Borise's website
email: lnborise@gmail.com
description: This website hosts Lena Borise's work in linguistics.
baseurl: "lnborise"
url:   https://lnborise.github.io
github_username: lnborise

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
permalink: /aboutme
permalink: /cv
permalink: /publications
permalink: /presentations

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
author:
  name: Lena Borise
  image: LB_upddd.jpg

social:
  name: Lena Borise
  links:
   - https://www.facebook.com/lena.borise
   - https://github.com/lnborise
   - https://www.researchgate.net/profile/Lena-Borise
   - https://uk.linkedin.com/in/lena-borise-8821a547
   - https://scholar.google.com/citations?hl=ru&user=TrvSdWIAAAAJ
   - https://nytud.academia.edu/LenaBorise
   - https://orcid.org/0000-0002-6356-7472
